version: "3.9"
services:
  postgres_cadastro:
    container_name: postgres_cadastro-ifood
    image: postgres:14
    environment:
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
    ports:
      - "5432:5432"